from .unet_model import UNet
from .ucaps22 import UCaps22
from .ucaps28 import UCaps28
from .segcaps_model import SegCaps
from .tiramisu_model import FCDenseNet
from .tiramisu_model import FCDenseNet57
from .tiramisu_model import FCDenseNet67
from .tiramisu_model import FCDenseNet103
from .scale_caps import ScaleCaps
from .wcaps import WCaps
from .ocrnet import HRNet_Mscale
from .deeper import DeeperX71
from .deepv3 import DeepV3PlusX71